version: '3.3'

services:
  app:
    build:
      context: ./conf
      dockerfile: nginx.dockerfile
    container_name: app_portofolio
    tty: true
    ports:
      - 8001:80
      - 4431:443
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  php:
    build:
      context: ./conf
      dockerfile: php.dockerfile
    container_name: php_portofolio
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=host.docker.internal
      - DB_PORT=3307
      - DB_DATABASE=app_one
      - DB_USERNAME=root
      - DB_PASSWORD=010203
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html:delegated
      - ./conf/php/config.ini:/usr/local/etc/php/conf.d/config.ini
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis_portofolio
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - laravel
  
  cron:
    build:
      context: ./conf
      dockerfile: cron.dockerfile
    container_name: cron_portofolio
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

#Docker Networks
networks:
  laravel:
    driver: bridge
