
version: '3.3'

services:
  app:
    build:
      context: ./conf
      dockerfile: nginx.dockerfile
    container_name: accounting_backend_dev_app
    tty: true
    ports:
      - 8001:80
      - 4431:443
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel
 
  php:
    build:
      context: ./conf
      dockerfile: php.dockerfile
    container_name: accounting_backend_dev_php
    env_file:
      - ./src/.env
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html:delegated
      - ./conf/php/config.ini:/usr/local/etc/php/conf.d/config.ini
    networks:
      - laravel
  
  cron:
    build:
      context: ./conf
      dockerfile: cron.dockerfile
    container_name: accounting_backend_dev_cron
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
#Docker Networks
networks:
  laravel:
    driver: bridge
