version: '3.3'

services:
  web:
    build:
      context: ./conf
      dockerfile: nginx.dockerfile
    container_name: container_name_web
    restart: unless-stopped
    tty: true
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html:delegated
      - ./data/nginx/log:/var/log/nginx
    networks:
      - network_name

  php:
    build:
      context: ./conf
      dockerfile: php.dockerfile
    container_name: container_name_php
    restart: unless-stopped
    env_file:
      - ./src/.env
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html:delegated
      - ./conf/php/config.ini:/usr/local/etc/php/conf.d/config.ini
    networks:
      - network_name

networks:
  network_name:
    external: true