version: '3.3'

services:
  web:
    build:
      context: ./conf
      dockerfile: nginx.dockerfile
    container_name: pbm_banuanta_staging_web
    tty: true
    ports:
      - 8005:80
    volumes:
      - ./src:/var/www/html:delegated
      - ./data/nginx/log:/var/log/nginx
    networks:
      - pbm_banuanta

  php:
    build:
      context: ./conf
      dockerfile: php.dockerfile
    container_name: pbm_banuanta_staging_php
    env_file:
      - ./src/.env
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html:delegated
      - ./conf/php/config.ini:/usr/local/etc/php/conf.d/config.ini
      - ./data/web/storage:/var/www/html/storage/app/public
      - ./data/web/log:/var/www/html/storage/logs
    networks:
      - pbm_banuanta

  cron:
    build:
      context: ./conf
      dockerfile: cron.dockerfile
    container_name: pbm_banuanta_staging_cron
    volumes:
      - ./src:/var/www/html
    networks:
      - pbm_banuanta
#Docker Networks
networks:
  pbm_banuanta:
    driver: bridge
