name: Auto Merge Staging Branch

on:
  pull_request:
    branches:
      - staging

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test code
      run: |
        # Add your build and test commands here
        echo "No testing required"

    - name: Merge pull request
      uses: peter-evans/pull-request-auto-merge@v3
      with:
        github-token: ${{ secrets.TOKEN }}
        merge-method: squash
        delete-branch: true
        commit-message: "Automatically merged pull request #${{ github.event.pull_request.number }} by ${github.event.pull_request.user.login}}"

    - name: Comment on merged pull request
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          :tada: This pull request has been automatically merged into the `staging` branch.
          :rocket: Thanks for your contribution!
